### ISSUE TITLE
Create workflow to test and verify pip install

### ISSUE THREAD

**Issue by rileym666** [dylankemp/pdfrw#2]

**Comment by DamFlancoz** [comment]
Use this trigger:
```
on:
  push:
    branches:
      - master
```
